### --- 1. Environment Setup --- ###
SCENARIO_NAME: "MCSLab"
DIMENSION: 2  # 2D (x, y)

# --- Access Point  ---
ACCESS_POINTS:
  # AP_ID 1
  AP_1:
    NAME: "AP_window"
    LOCATION_M: [-10, -0.5]

  # AP_ID 2
  AP_2:
    NAME: "AP_North"
    LOCATION_M: [8, -5]

  # AP_ID 3
  AP_3:
    NAME: "AP_East"
    LOCATION_M: [-1.5, 7]

  # AP_ID 4
  AP_4:
    NAME: "AP_Northwest"
    LOCATION_M: [-3.5, -8]

# --- Grid Generation Parameters ---
GRID_RESOLUTION_M: 0.5  
BUFFER_DISTANCE_M: 0



### --- 2. System Setup --- ###
CSI_DIMENSIONS:
  NUM_RX_ANTENNAS: 3                      # notation: N
  NUM_SUBCARRIERS: 21                     # notation: M @@@
  
# --- Frequency & Inter-element Spacing ---
CARRIER_FREQUENCY_HZ: 5180000000.0
CHANNEL_BANDWIDTH_HZ: 20000000.0          # notation: B
ANTENNA_DISTANCE: 0.03                    # notation: d

# --- Packeting & Aggregation ---
NUM_SAMPLE: 2                           # notation: T
NUM_PACKET: 1                           # notation: P

### --- 3. Controller Setup --- ###
MIN_TRAJ_TO_TRAIN: 7
BATCH_SIZE: 10
TRAINING_EPOCHS: 50

CSItoTRAJECTORY_SLEEP_S: 0.1
TRANSFORMER_SLEEP_S: 0.1

### --- 4. Transformer Parameter --- ###
EMB_SIZE: 512
HEADS: 8
LAYERS: 6
DROPOUT: 0.1
D_FF: 2048                                # Feed Forward Dimension

NOAMOPT_FACTOR: 1.0
NOAMOPT_WARMUP_STEPS: 4000