# config.yaml

### --- LOOP --- ###
LOOP: False

### --- System Mode --- ###
#SYSTEM_MODE: 'BASELINE'
SYSTEM_MODE: 'PROPOSED'

### --- Environment & Trajectory --- ###
DATASET_FOLDER: "dataset_office_8AP"
ENV_CONFIG: "env_config.yaml"
HMATRIX_LIST:
  - "NLoS_t799_ch36_ant3" #NLoS_t150_ch36_ant3, train_direct, NLoS_t799_ch36_ant3, train_wander

### --- Grid Generation Parameters --- ###
GRID_RESOLUTION_M: 0.5
BUFFER_DISTANCE_M: 0

### --- 2. System Setup --- ###
CSI_DIMENSIONS:
  NUM_RX_ANTENNAS: 3                      # notation: N
  NUM_SUBCARRIERS: 21                     # notation: M       ch36: 21,       ch106: 81
  
### --- Frequency & Inter-element Spacing --- ###
CARRIER_FREQUENCY_HZ: 5180000000.0        # center frequency  ch36: 518,      ch106: 553
CHANNEL_BANDWIDTH_HZ: 20000000.0          # notation: B       ch36: 20,       ch106: 80
ANTENNA_DISTANCE: 0.02899                  # notation: d       ch36: 0.02899,  ch106: 0.0273

### --- Packeting & Aggregation --- ###
NUM_SAMPLE: 15                            # notation: T
NUM_PACKET: 1                             # notation: P

### --- Ablation Study --- ###
BASELINE_AOA_METHOD: 'mmp'              # 'music' or 'mmp'
USE_SOFT_EM: True
USE_TOF_GAIN_WEIGHT: True
USE_NEURAL: True

### --- neural worker / runtime --- ###
NEURAL_SLEEP: 0.05
NEURAL_BATCH_SIZE: 32
NEURAL_WINDOW_SIZE: 16
NEURAL_SEQUENCE_BUFFER_CAPACITY: 128

NEURAL_UPDATES_PER_BATCH: 1

NEURAL_UPDATE_INTERVAL: 1
NEURAL_SAVE_INTERVAL: 50
NEURAL_MIN_UPDATES: 0

### --- debug --- ###
SAVE_NEURAL_DEBUG: true
NEURAL_DEBUG_DIR: output/neural_debug
NEURAL_DEBUG_SAVE_INTERVAL: 20

### --- optimization --- ###
LATENT_DIM: 128
NEURAL_NUM_HEADS: 4

LR: 0.0005
WEIGHT_DECAY: 0.0001
GRAD_CLIP_NORM: 1.0

SCORE_LOSS_TYPE: huber
HUBER_BETA: 1.0
LOSS_WEIGHT_SCORE: 1.0
LOSS_WEIGHT_SMOOTH: 0.0


# DEBUG
ACCESS_POINTS:
  - ap1
  - ap2
  - ap3
  - ap4
  - ap5
  - ap6
  - ap7
  - ap8