### --- LOOP --- ###
LOOP: False

### --- System Mode --- ###
#SYSTEM_MODE: 'BASELINE'
SYSTEM_MODE: 'PROPOSED'

### --- Environment & Trajectory --- ###
DATASET_FOLDER: "dataset_easyspace"
ENV_CONFIG: "env_config.yaml"
HMATRIX_LIST: 
  - "Hmatrix_2"

# --- Grid Generation Parameters ---
GRID_RESOLUTION_M: 0.5
BUFFER_DISTANCE_M: 0

### --- 2. System Setup --- ###
CSI_DIMENSIONS:
  NUM_RX_ANTENNAS: 3                      # notation: N
  NUM_SUBCARRIERS: 21                     # notation: M
  
# --- Frequency & Inter-element Spacing ---
CARRIER_FREQUENCY_HZ: 5180000000.0
CHANNEL_BANDWIDTH_HZ: 20000000.0          # notation: B
ANTENNA_DISTANCE: 0.03                    # notation: d

# --- Packeting & Aggregation ---
NUM_SAMPLE: 182                           # notation: T
NUM_PACKET: 1                          # notation: P

### --- 3. Controller Setup --- ###
MIN_TRAJ_TO_TRAIN: 20000
BATCH_SIZE: 10
TRAINING_EPOCHS: 50
NUM_CANDIDATES: 7

CSItoTRAJECTORY_SLEEP_S: 0.1
TRANSFORMER_SLEEP_S: 0.1

### --- 4. Transformer Parameter --- ###
EMB_SIZE: 512
HEADS: 8
LAYERS: 6
DROPOUT: 0.1
D_FF: 2048                                # Feed Forward Dimension

NOAMOPT_FACTOR: 1.0
NOAMOPT_WARMUP_STEPS: 4000
BUFFER_LEN: 20
