### --- 1. Environment Setup --- ###
SCENARIO_NAME: "MCSLab"
DIMENSION: 2  # 2D (x, y)

# --- Access Point  ---
ACCESS_POINTS:
  # AP_ID 1
  AP_1:
    NAME: "AP_Southwest"
    LOCATION_M: [0, 0]
    ORIENTATION_DEG: 45.0

  # AP_ID 2
  AP_2:
    NAME: "AP_North"
    LOCATION_M: [2, 3]
    ORIENTATION_DEG: 270.0

  # AP_ID 3
  AP_3:
    NAME: "AP_East"
    LOCATION_M: [4, 0]
    ORIENTATION_DEG: 180.0

  # AP_ID 4
  AP_4:
    NAME: "AP_Northwest"
    LOCATION_M: [0, 2]
    ORIENTATION_DEG: 325.0

# --- Grid Generation Parameters ---
GRID_RESOLUTION_M: 1  
BUFFER_DISTANCE_M: 0



### --- 2. System Setup --- ###
CSI_DIMENSIONS:
  NUM_RX_ANTENNAS: 3                      # notation: N
  NUM_SUBCARRIERS: 30                     # notation: M
  
# --- Frequency & Inter-element Spacing ---
CARRIER_FREQUENCY_HZ: 5.0 * 1000000000 
CHANNEL_BANDWIDTH_HZ: 80.0 * 1000000      # notation: B
ANTENNAS_DISTENCE: 0.03                   # notation: d

# --- Packeting & Aggregation ---
NUM_SAMPLE: 100                           # notation: T
NUM_PACKET: 15                            # notation: P