# --- System & Hardware Specifications ---
CSI_DIMENSIONS:
  NUM_RX_ANTENNAS: 3                      # notation: N
  NUM_SUBCARRIERS: 30                     # notation: M
  
# --- Frequency & Inter-element Spacing ---
CARRIER_FREQUENCY_GHZ: 5.0 * 1000000000 
CHANNEL_BANDWIDTH_MHZ: 80.0 * 1000000     # notation: B
ANTENNAS_DISTENCE: 0.03                   # notation: d

# --- Packeting & Aggregation ---
NUM_SAMPLE: 100                           # notation: T
NUM_PACKET: 15                            # notation: P

